apiVersion: v2
type: application
name: vault-operator
version: 1.8.1
appVersion: 1.8.0
description: A Helm chart for banzaicloud/bank-vaults Vault operator
home: https://banzaicloud.com/products/bank-vaults/
sources:
  - https://github.com/hashicorp/vault
  - https://github.com/banzaicloud/bank-vaults
  - https://github.com/banzaicloud/banzai-charts
maintainers:
  - name: Banzai Cloud
    email: info@banzaicloud.com
dependencies:
- name: etcd-operator
  version: 0.11.0
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: etcd-operator.enabled
