apiVersion: v2
type: application
name: vault-operator
version: 1.15.6
appVersion: 1.15.2
description: A Helm chart for banzaicloud/bank-vaults Vault operator
icon: https://raw.githubusercontent.com/banzaicloud/bank-vaults/main/docs/images/logo/bank-vaults-logo.svg
home: https://banzaicloud.com/products/bank-vaults/
sources:
  - https://github.com/hashicorp/vault
  - https://github.com/banzaicloud/bank-vaults
maintainers:
  - name: Banzai Cloud
    email: info@banzaicloud.com
