apiVersion: v1
description: A Helm chart for Vault, a tool for managing secrets
name: vault
version: 0.5.14
appVersion: 0.11.1
home: https://www.vaultproject.io/
icon: https://www.vaultproject.io/assets/images/mega-nav/logo-vault-0f83e3d2.svg
sources:
  - https://github.com/hashicorp/vault
  - https://github.com/banzaicloud/bank-vaults
  - https://github.com/banzaicloud/banzai-charts
