apiVersion: v1
name: vault
version: 1.11.1
appVersion: 1.11.0
description: A Helm chart for Vault, a tool for managing secrets
home: https://www.vaultproject.io/
icon: https://www.vaultproject.io/assets/images/mega-nav/logo-vault-0f83e3d2.svg
sources:
  - https://github.com/hashicorp/vault
  - https://github.com/banzaicloud/bank-vaults
maintainers:
  - name: Banzai Cloud
    email: info@banzaicloud.com
