blank_issues_enabled: true
contact_links:
  - name: ğŸ“– Documentation enhancement
    url: https://github.com/bank-vaults/bank-vaults.dev/issues
    about: Suggest an improvement to the documentation

  - name: â“ Ask a question
    url: https://github.com/orgs/bank-vaults/discussions/new?category=q-a
    about: Ask and discuss questions with other Bank-Vaults community members

  - name: ğŸ“š Documentation
    url: https://bank-vaults.dev/docs
    about: Check the documentation for help

  - name: ğŸ’¬ Slack channel
    url: https://cloud-native.slack.com/archives/C078PHYK38W/
    about: Please ask and answer questions here
