apiVersion: v1
kind: Secret
metadata:
  name: sample-secret
  annotations:
    vault.security.banzaicloud.io/vault-addr: "https://vault.default.svc.cluster.local:8200"
    vault.security.banzaicloud.io/vault-role: "default"
    vault.security.banzaicloud.io/vault-tls-secret: vault-tls
    # vault.security.banzaicloud.io/vault-skip-verify: "true"
    vault.security.banzaicloud.io/vault-path: "kubernetes"
    vault.security.banzaicloud.io/inline-mutation: "true"
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJ2YXVsdDpzZWNyZXQvZGF0YS9kb2NrZXJyZXBvI0RPQ0tFUl9SRVBPX1VTRVIiLCJwYXNzd29yZCI6InZhdWx0OnNlY3JldC9kYXRhL2RvY2tlcnJlcG8jRE9DS0VSX1JFUE9fUEFTU1dPUkQiLCJhdXRoIjoiZG1GMWJIUTZjMlZqY21WMEwyUmhkR0V2Wkc5amEyVnljbVZ3YnlORVQwTkxSVkpmVWtWUVQxOVZVMFZTT25aaGRXeDBPbk5sWTNKbGRDOWtZWFJoTDJSdlkydGxjbkpsY0c4alJFOURTMFZTWDFKRlVFOWZVRUZUVTFkUFVrUT0ifX19
  vaultdata: dmF1bHQ6c2VjcmV0L2RhdGEvYWNjb3VudHMvYXdzI0FXU19BQ0NFU1NfS0VZX0lE
  inline: SW5saW5lOiAke3ZhdWx0OnNlY3JldC9kYXRhL2FjY291bnRzL2F3cyNBV1NfQUNDRVNTX0tFWV9JRH0gQVdTX0FDQ0VTU19LRVlfSUQ=
