apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: vault-secrets-syncer
    app.kubernetes.io/name: service
    app.kubernetes.io/instance: vault-secrets-syncer-metrics-service
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: controller
    app.kubernetes.io/part-of: controller
    app.kubernetes.io/managed-by: kustomize
  name: vault-secrets-syncer-metrics-service
  namespace: system
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    control-plane: vault-secrets-syncer
